name: App Heartbeat Monitor

on:
  schedule:
    # Runs every 4 hours.
    - cron: '0 */4 * * *'
  # Allows to run manually
  workflow_dispatch:

jobs:
  check-and-wake:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Caches dependencies
          cache: 'pip'

      - name: Install Selenium and Chrome
        run: |
          pip install selenium webdriver-manager brotli

      - name: Run Heartbeat Script
        env:
          # Add your Streamlit URL to GitHub Repo Secrets
          STREAMLIT_URL: ${{ secrets.STREAMLIT_URL }}
        run: python scripts/heartbeat.py